
import type { Metadata } from "next";
import "../globals.css";
import React from 'react'


import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
          <Navbar/>
          <div className={"px-14 pt-0 dark"}>
              {children}
          </div>

      </>

  );
}
