import type { Metadata } from "next";
import "../globals.css";


import {ThemeProvider} from "@/components/ThemeProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`kanit-regular antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <div className={"px-14 pt-8"}>
              {children}
          </div>
      </ThemeProvider>


      </body>
    </html>
  );
}
