import type { Metadata } from "next";
import "../globals.css";


import {ThemeProvider} from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <div className={"px-14 pt-4"}>
              {children}
          </div>
      </ThemeProvider>
  );
}
