import type { Metadata } from "next";
import "./globals.css";


import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`kanit-regular antialiased`}
      >
      <Navbar/>
        <div className={"px-14 pt-8"}>
            {children}
        </div>

      </body>
    </html>
  );
}
