
import type { Metadata } from "next";
import "../globals.css";
import React from "react";
import Navbar from "@/components/Navbar";
import {updateSession} from "@/lib/sessions";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <>
        <Navbar/>

        <div className={"px-14 pt-4"}>
          {children}
        </div>
      </>
  );
}
